name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - name: Install test dependencies
        run: pip install -r requirements_test.txt ruff
      - name: Ruff
        run: ruff check custom_components tests
      - name: Run tests
        run: pytest -q
